# Section 1 Where in the Genome does replication start?

In [11]:
import numpy as np

matrix = np.array([[0,1,1,1],[1,0,1,0],[1,1,0,1],[1,0,1,0]])
#multiple the same matirix multiple times
print(np.linalg.matrix_power(matrix, 4))


[[15  9 14  9]
 [ 9 10  9 10]
 [14  9 15  9]
 [ 9 10  9 10]]


In [2]:
import pandas as pd
import numpy as np

## 1.2

In [3]:
#statistic the length of the genome
def pattern_count(text: str, pattern: str) -> int:
    pattern_length = len(pattern)
    count = 0
    for i in range(len(text) - pattern_length + 1):
        if text[i:i+pattern_length] == pattern:
            count += 1
    return count

### test
text = 'AGCGTGCCGAAATTT'
pattern = 'TTT'


# 1.3

In [4]:
def frequent_words(text: str, k: int) -> list[str]:
    """Find the most frequent k-mers in a given text."""
    patterns = {}
    frequent_patterns = []
    for i in range(len(text) - k + 1):
        pattern = text[i:i+k]
        if patterns.get(pattern):
            patterns[pattern] += 1
        else:
            patterns[pattern] = 1
    # find patterns with most occurrences
    max_value = find_max_value(patterns)
    for pattern, value in patterns.items():
        if value == max_value:
            frequent_patterns.append(pattern)

    return frequent_patterns

def find_max_value(dict: dict) -> int:
    return max(dict.values())

seq = 'ACGTTGCATGTCGCATGATGCATGAGAGCT'
k = 4
print(frequent_words(seq, k))

['GCAT', 'CATG']


![overlap_words](../Figure/Figure/C1/overlap_words.png)
As stated, a k-mer might be random substring of another larger k-mer

![random_kmer](../Figure/Figure/C1/Non_Overlapping.png)


如上图, 我们把问题简化成目标k-mer可以插入的位置, 那么就是N-t个可能位置。注意这里没有考虑overlap的情况！

1.3 Reverse DNA

In [7]:
def reverse_complement(pattern: str) -> str:
    """Calculate the reverse complement of a DNA pattern."""
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}
    return ''.join(complement[base] for base in reversed(pattern))

test_input = 'AAAACCCGGT'
print(reverse_complement(test_input))

# Insert your pattern_matching function here, along with any subroutines you need
def pattern_matching(pattern: str, genome: str) -> list[int]:
    """Find all occurrences of a pattern in a genome."""
    positions = []
    for i in range(len(genome) - len(pattern) + 1):
        if genome[i:i+len(pattern)] == pattern:
            positions.append(i)
    return positions

test_pattern = 'ATA'
test_genome = 'ATATATA'
print(pattern_matching(test_pattern, test_genome))



ACCGGGTTTT
[0, 2, 4]


for the whole genoem


In [15]:
with open('./Vibrio_cholerae.txt', 'r') as genome:
    genome_seq = genome.read()
test_pattern = 'ATGATCAAG'
start_pos = pattern_matching(test_pattern, genome_seq)
#output space separated integers
print(' '.join(map(str, start_pos)))


116556 149355 151913 152013 152394 186189 194276 200076 224527 307692 479770 610980 653338 679985 768828 878903 985368


Next we want to find k-mers that occur more than t times in a string of L.  
Sample Input 1:  
CGGACTCGACAGATGTGAAGAACGACAATGTGAAGACTCGACACGACAGAGTGAAGAGAAGAGGAAACATTGTAA  
5 50 4  